title: varkor's blog
description: >-
  A small blog about Rust, type theory and mathematics.
baseurl: "/blog"
url: "https://varkor.github.io"
github_username:  varkor

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%d %B, %Y"

google_analytics: UA-24316761-2

collections:
  drafts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
      type: drafts
    values:
      sitemap: false
      noindex: true